<a href="https://colab.research.google.com/github/apple-pie-h/ICES-AI-bootcamp/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Assignment

In [19]:
#importing numpy
import numpy as np

##Exercise 1: Load and save numpy array from memory to disk

In [4]:
a=np.array([1,2,3])
print(a)
b=np.array([[1,2,3],[4,5,6]])
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [5]:
np.save('a.npy',a) #to save single numpy array

In [7]:
l=np.load('a.npy')
print(l)

[1 2 3]


In [12]:
np.savez('arr.npz',a,b) #to save multiple numpy array
l=np.load('arr.npz')
print(l)

NpzFile 'arr.npz' with keys: arr_0, arr_1


In [13]:
print(l.files)

['arr_0', 'arr_1']


In [17]:
print(l['arr_0'])

[1 2 3]


In [18]:
print(l['arr_1'])

[[1 2 3]
 [4 5 6]]


##Exercise 2: Implement an image filter using numpy array manipulation

##Exercise 3: Implement 2d rotation of image using numpy

##Exercise 4: Review the important concepts and do some challenges in each section